name: Docker
on:
  push:
    branches: ["master"]

jobs:
  build:
    name: Build & puch docker image
    runs-on: ubuntu-latest
    env:
      IMG_NAME: ${{ github.repository }}
      IMG_VERSION: 0.0.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t docker.io/${{ github.repository }}:${{ IMG_VERSION }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-actions@0.28.0
        with:
          image-ref: 'docker.io/${{ github.repository }}:0.0.3' # change version
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL.HIGH'

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ github.repository }}:${{ IMG_VERSION }}